package:
  name: cdat_compute_graph
  version: 1.2.1

source:
    git_rev: master
    git_url: https://github.com/cdat/cdat_compute_graph

requirements:
  build:
    - python
    - setuptools
    - nose
    - coverage
    - pip

  run:
    - python
    - cdms2
    - compute_graph

build:
    number: 0
    noarch: python
    script: python -m pip install --no-deps --ignore-installed .

about:
  home: https://github.com/cdat/compute_graph
  license: BSD
  summary: "A package that extends compute_graph with nodes that handle cdms variables and operations"
